services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wp_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${WORDPRESS_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
  wordpress_data:

networks:
  wp_network:
